# Find the Log4cplus includes and library

FIND_PATH(LOG4CPLUS_INCLUDE_DIR log4cplus/logger.h
    /usr/local/include
    /usr/include
)

FIND_LIBRARY(LOG4CPLUS_LIBRARY log4cplus
    ${LOG4CPLUS_INCLUDE_DIR}/../lib
    /usr/local/lib
    /usr/lib)

IF (LOG4CPLUS_INCLUDE_DIR AND LOG4CPLUS_LIBRARY)
    SET(LOG4CPLUS_FOUND TRUE)
ENDIF (LOG4CPLUS_INCLUDE_DIR AND LOG4CPLUS_LIBRARY)

IF (LOG4CPLUS_FOUND)
    MESSAGE(STATUS "Found LOG4CPLUS INCLUDE: ${LOG4CPLUS_INCLUDE_DIR}")
    MESSAGE(STATUS "Found LOG4CPLUS LIBRARY: ${LOG4CPLUS_LIBRARY}")
    SET(LOG4CPLUS_LIBRARIES ${LOG4CPLUS_LIBRARY})
ELSE (LOG4CPLUS_FOUND)
    IF (LOG4CPLUS_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "LOG4CPLUS not found")
    ELSE (LOG4CPLUS_FIND_REQUIRED)
        MESSAGE(STATUS "LOG4CPLUS not found")
    ENDIF (LOG4CPLUS_FIND_REQUIRED)
ENDIF (LOG4CPLUS_FOUND)

MARK_AS_ADVANCED(LOG4CPLUS_INCLUDE_DIR LOG4CPLUS_LIBRARY)
